CREATE DATABASE UpperToolsProject;
CREATE TABLE [dbo].[CnpjResponse](
	[Cnpj] [varchar](50) NOT NULL,
	[Nome] [varchar](250) NULL,
	[NomeFantasia] [varchar](250) NULL,
	[Tipo] [varchar](50) NULL,
	[Uf] [varchar](50) NULL,
 CONSTRAINT [PK_CnpjResponse] PRIMARY KEY CLUSTERED 
(
	[Cnpj] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO